/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as GetStartedRouteImport } from './routes/get-started'
import { Route as DimensionsRouteImport } from './routes/dimensions'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShyamIndexRouteImport } from './routes/shyam.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ShyamVoiceRouteImport } from './routes/shyam.voice'
import { Route as ShyamUidSearchRouteImport } from './routes/shyam.uid-search'
import { Route as ShyamPostsRouteImport } from './routes/shyam.posts'
import { Route as ShyamDashboardRouteImport } from './routes/shyam.dashboard'
import { Route as ShyamBookingsRouteImport } from './routes/shyam.bookings'
import { Route as SessionsVipPlatinumRouteImport } from './routes/sessions.vip-platinum'
import { Route as SessionsSilverPrimeLiteRouteImport } from './routes/sessions.silver-prime-lite'
import { Route as SessionsSilverPrimeRouteImport } from './routes/sessions.silver-prime'
import { Route as SessionsSilverRouteImport } from './routes/sessions.silver'
import { Route as SessionsPlatinumRouteImport } from './routes/sessions.platinum'
import { Route as SessionsGoldPrimeRouteImport } from './routes/sessions.gold-prime'
import { Route as SessionsGoldRouteImport } from './routes/sessions.gold'
import { Route as SessionsBronzeRouteImport } from './routes/sessions.bronze'
import { Route as DimensionsSlugRouteImport } from './routes/dimensions.$slug'
import { Route as AppVoiceRoomRouteImport } from './routes/app.voice-room'
import { Route as AppBookRouteImport } from './routes/app.book'
import { Route as AppUidUidRouteImport } from './routes/app.uid.$uid'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const GetStartedRoute = GetStartedRouteImport.update({
  id: '/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const DimensionsRoute = DimensionsRouteImport.update({
  id: '/dimensions',
  path: '/dimensions',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShyamIndexRoute = ShyamIndexRouteImport.update({
  id: '/shyam/',
  path: '/shyam/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShyamVoiceRoute = ShyamVoiceRouteImport.update({
  id: '/shyam/voice',
  path: '/shyam/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const ShyamUidSearchRoute = ShyamUidSearchRouteImport.update({
  id: '/shyam/uid-search',
  path: '/shyam/uid-search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShyamPostsRoute = ShyamPostsRouteImport.update({
  id: '/shyam/posts',
  path: '/shyam/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ShyamDashboardRoute = ShyamDashboardRouteImport.update({
  id: '/shyam/dashboard',
  path: '/shyam/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ShyamBookingsRoute = ShyamBookingsRouteImport.update({
  id: '/shyam/bookings',
  path: '/shyam/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsVipPlatinumRoute = SessionsVipPlatinumRouteImport.update({
  id: '/vip-platinum',
  path: '/vip-platinum',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsSilverPrimeLiteRoute = SessionsSilverPrimeLiteRouteImport.update({
  id: '/silver-prime-lite',
  path: '/silver-prime-lite',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsSilverPrimeRoute = SessionsSilverPrimeRouteImport.update({
  id: '/silver-prime',
  path: '/silver-prime',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsSilverRoute = SessionsSilverRouteImport.update({
  id: '/silver',
  path: '/silver',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsPlatinumRoute = SessionsPlatinumRouteImport.update({
  id: '/platinum',
  path: '/platinum',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsGoldPrimeRoute = SessionsGoldPrimeRouteImport.update({
  id: '/gold-prime',
  path: '/gold-prime',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsGoldRoute = SessionsGoldRouteImport.update({
  id: '/gold',
  path: '/gold',
  getParentRoute: () => SessionsRoute,
} as any)
const SessionsBronzeRoute = SessionsBronzeRouteImport.update({
  id: '/bronze',
  path: '/bronze',
  getParentRoute: () => SessionsRoute,
} as any)
const DimensionsSlugRoute = DimensionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DimensionsRoute,
} as any)
const AppVoiceRoomRoute = AppVoiceRoomRouteImport.update({
  id: '/app/voice-room',
  path: '/app/voice-room',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBookRoute = AppBookRouteImport.update({
  id: '/app/book',
  path: '/app/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUidUidRoute = AppUidUidRouteImport.update({
  id: '/app/uid/$uid',
  path: '/app/uid/$uid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dimensions': typeof DimensionsRouteWithChildren
  '/get-started': typeof GetStartedRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/app/book': typeof AppBookRoute
  '/app/voice-room': typeof AppVoiceRoomRoute
  '/dimensions/$slug': typeof DimensionsSlugRoute
  '/sessions/bronze': typeof SessionsBronzeRoute
  '/sessions/gold': typeof SessionsGoldRoute
  '/sessions/gold-prime': typeof SessionsGoldPrimeRoute
  '/sessions/platinum': typeof SessionsPlatinumRoute
  '/sessions/silver': typeof SessionsSilverRoute
  '/sessions/silver-prime': typeof SessionsSilverPrimeRoute
  '/sessions/silver-prime-lite': typeof SessionsSilverPrimeLiteRoute
  '/sessions/vip-platinum': typeof SessionsVipPlatinumRoute
  '/shyam/bookings': typeof ShyamBookingsRoute
  '/shyam/dashboard': typeof ShyamDashboardRoute
  '/shyam/posts': typeof ShyamPostsRoute
  '/shyam/uid-search': typeof ShyamUidSearchRoute
  '/shyam/voice': typeof ShyamVoiceRoute
  '/app/': typeof AppIndexRoute
  '/shyam/': typeof ShyamIndexRoute
  '/app/uid/$uid': typeof AppUidUidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dimensions': typeof DimensionsRouteWithChildren
  '/get-started': typeof GetStartedRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/app/book': typeof AppBookRoute
  '/app/voice-room': typeof AppVoiceRoomRoute
  '/dimensions/$slug': typeof DimensionsSlugRoute
  '/sessions/bronze': typeof SessionsBronzeRoute
  '/sessions/gold': typeof SessionsGoldRoute
  '/sessions/gold-prime': typeof SessionsGoldPrimeRoute
  '/sessions/platinum': typeof SessionsPlatinumRoute
  '/sessions/silver': typeof SessionsSilverRoute
  '/sessions/silver-prime': typeof SessionsSilverPrimeRoute
  '/sessions/silver-prime-lite': typeof SessionsSilverPrimeLiteRoute
  '/sessions/vip-platinum': typeof SessionsVipPlatinumRoute
  '/shyam/bookings': typeof ShyamBookingsRoute
  '/shyam/dashboard': typeof ShyamDashboardRoute
  '/shyam/posts': typeof ShyamPostsRoute
  '/shyam/uid-search': typeof ShyamUidSearchRoute
  '/shyam/voice': typeof ShyamVoiceRoute
  '/app': typeof AppIndexRoute
  '/shyam': typeof ShyamIndexRoute
  '/app/uid/$uid': typeof AppUidUidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dimensions': typeof DimensionsRouteWithChildren
  '/get-started': typeof GetStartedRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/terms': typeof TermsRoute
  '/app/book': typeof AppBookRoute
  '/app/voice-room': typeof AppVoiceRoomRoute
  '/dimensions/$slug': typeof DimensionsSlugRoute
  '/sessions/bronze': typeof SessionsBronzeRoute
  '/sessions/gold': typeof SessionsGoldRoute
  '/sessions/gold-prime': typeof SessionsGoldPrimeRoute
  '/sessions/platinum': typeof SessionsPlatinumRoute
  '/sessions/silver': typeof SessionsSilverRoute
  '/sessions/silver-prime': typeof SessionsSilverPrimeRoute
  '/sessions/silver-prime-lite': typeof SessionsSilverPrimeLiteRoute
  '/sessions/vip-platinum': typeof SessionsVipPlatinumRoute
  '/shyam/bookings': typeof ShyamBookingsRoute
  '/shyam/dashboard': typeof ShyamDashboardRoute
  '/shyam/posts': typeof ShyamPostsRoute
  '/shyam/uid-search': typeof ShyamUidSearchRoute
  '/shyam/voice': typeof ShyamVoiceRoute
  '/app/': typeof AppIndexRoute
  '/shyam/': typeof ShyamIndexRoute
  '/app/uid/$uid': typeof AppUidUidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dimensions'
    | '/get-started'
    | '/privacy'
    | '/refund'
    | '/sessions'
    | '/terms'
    | '/app/book'
    | '/app/voice-room'
    | '/dimensions/$slug'
    | '/sessions/bronze'
    | '/sessions/gold'
    | '/sessions/gold-prime'
    | '/sessions/platinum'
    | '/sessions/silver'
    | '/sessions/silver-prime'
    | '/sessions/silver-prime-lite'
    | '/sessions/vip-platinum'
    | '/shyam/bookings'
    | '/shyam/dashboard'
    | '/shyam/posts'
    | '/shyam/uid-search'
    | '/shyam/voice'
    | '/app/'
    | '/shyam/'
    | '/app/uid/$uid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dimensions'
    | '/get-started'
    | '/privacy'
    | '/refund'
    | '/sessions'
    | '/terms'
    | '/app/book'
    | '/app/voice-room'
    | '/dimensions/$slug'
    | '/sessions/bronze'
    | '/sessions/gold'
    | '/sessions/gold-prime'
    | '/sessions/platinum'
    | '/sessions/silver'
    | '/sessions/silver-prime'
    | '/sessions/silver-prime-lite'
    | '/sessions/vip-platinum'
    | '/shyam/bookings'
    | '/shyam/dashboard'
    | '/shyam/posts'
    | '/shyam/uid-search'
    | '/shyam/voice'
    | '/app'
    | '/shyam'
    | '/app/uid/$uid'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dimensions'
    | '/get-started'
    | '/privacy'
    | '/refund'
    | '/sessions'
    | '/terms'
    | '/app/book'
    | '/app/voice-room'
    | '/dimensions/$slug'
    | '/sessions/bronze'
    | '/sessions/gold'
    | '/sessions/gold-prime'
    | '/sessions/platinum'
    | '/sessions/silver'
    | '/sessions/silver-prime'
    | '/sessions/silver-prime-lite'
    | '/sessions/vip-platinum'
    | '/shyam/bookings'
    | '/shyam/dashboard'
    | '/shyam/posts'
    | '/shyam/uid-search'
    | '/shyam/voice'
    | '/app/'
    | '/shyam/'
    | '/app/uid/$uid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DimensionsRoute: typeof DimensionsRouteWithChildren
  GetStartedRoute: typeof GetStartedRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  SessionsRoute: typeof SessionsRouteWithChildren
  TermsRoute: typeof TermsRoute
  AppBookRoute: typeof AppBookRoute
  AppVoiceRoomRoute: typeof AppVoiceRoomRoute
  ShyamBookingsRoute: typeof ShyamBookingsRoute
  ShyamDashboardRoute: typeof ShyamDashboardRoute
  ShyamPostsRoute: typeof ShyamPostsRoute
  ShyamUidSearchRoute: typeof ShyamUidSearchRoute
  ShyamVoiceRoute: typeof ShyamVoiceRoute
  AppIndexRoute: typeof AppIndexRoute
  ShyamIndexRoute: typeof ShyamIndexRoute
  AppUidUidRoute: typeof AppUidUidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-started': {
      id: '/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof GetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dimensions': {
      id: '/dimensions'
      path: '/dimensions'
      fullPath: '/dimensions'
      preLoaderRoute: typeof DimensionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shyam/': {
      id: '/shyam/'
      path: '/shyam'
      fullPath: '/shyam/'
      preLoaderRoute: typeof ShyamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shyam/voice': {
      id: '/shyam/voice'
      path: '/shyam/voice'
      fullPath: '/shyam/voice'
      preLoaderRoute: typeof ShyamVoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shyam/uid-search': {
      id: '/shyam/uid-search'
      path: '/shyam/uid-search'
      fullPath: '/shyam/uid-search'
      preLoaderRoute: typeof ShyamUidSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shyam/posts': {
      id: '/shyam/posts'
      path: '/shyam/posts'
      fullPath: '/shyam/posts'
      preLoaderRoute: typeof ShyamPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shyam/dashboard': {
      id: '/shyam/dashboard'
      path: '/shyam/dashboard'
      fullPath: '/shyam/dashboard'
      preLoaderRoute: typeof ShyamDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shyam/bookings': {
      id: '/shyam/bookings'
      path: '/shyam/bookings'
      fullPath: '/shyam/bookings'
      preLoaderRoute: typeof ShyamBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/vip-platinum': {
      id: '/sessions/vip-platinum'
      path: '/vip-platinum'
      fullPath: '/sessions/vip-platinum'
      preLoaderRoute: typeof SessionsVipPlatinumRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/silver-prime-lite': {
      id: '/sessions/silver-prime-lite'
      path: '/silver-prime-lite'
      fullPath: '/sessions/silver-prime-lite'
      preLoaderRoute: typeof SessionsSilverPrimeLiteRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/silver-prime': {
      id: '/sessions/silver-prime'
      path: '/silver-prime'
      fullPath: '/sessions/silver-prime'
      preLoaderRoute: typeof SessionsSilverPrimeRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/silver': {
      id: '/sessions/silver'
      path: '/silver'
      fullPath: '/sessions/silver'
      preLoaderRoute: typeof SessionsSilverRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/platinum': {
      id: '/sessions/platinum'
      path: '/platinum'
      fullPath: '/sessions/platinum'
      preLoaderRoute: typeof SessionsPlatinumRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/gold-prime': {
      id: '/sessions/gold-prime'
      path: '/gold-prime'
      fullPath: '/sessions/gold-prime'
      preLoaderRoute: typeof SessionsGoldPrimeRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/gold': {
      id: '/sessions/gold'
      path: '/gold'
      fullPath: '/sessions/gold'
      preLoaderRoute: typeof SessionsGoldRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/sessions/bronze': {
      id: '/sessions/bronze'
      path: '/bronze'
      fullPath: '/sessions/bronze'
      preLoaderRoute: typeof SessionsBronzeRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/dimensions/$slug': {
      id: '/dimensions/$slug'
      path: '/$slug'
      fullPath: '/dimensions/$slug'
      preLoaderRoute: typeof DimensionsSlugRouteImport
      parentRoute: typeof DimensionsRoute
    }
    '/app/voice-room': {
      id: '/app/voice-room'
      path: '/app/voice-room'
      fullPath: '/app/voice-room'
      preLoaderRoute: typeof AppVoiceRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/book': {
      id: '/app/book'
      path: '/app/book'
      fullPath: '/app/book'
      preLoaderRoute: typeof AppBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/uid/$uid': {
      id: '/app/uid/$uid'
      path: '/app/uid/$uid'
      fullPath: '/app/uid/$uid'
      preLoaderRoute: typeof AppUidUidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DimensionsRouteChildren {
  DimensionsSlugRoute: typeof DimensionsSlugRoute
}

const DimensionsRouteChildren: DimensionsRouteChildren = {
  DimensionsSlugRoute: DimensionsSlugRoute,
}

const DimensionsRouteWithChildren = DimensionsRoute._addFileChildren(
  DimensionsRouteChildren,
)

interface SessionsRouteChildren {
  SessionsBronzeRoute: typeof SessionsBronzeRoute
  SessionsGoldRoute: typeof SessionsGoldRoute
  SessionsGoldPrimeRoute: typeof SessionsGoldPrimeRoute
  SessionsPlatinumRoute: typeof SessionsPlatinumRoute
  SessionsSilverRoute: typeof SessionsSilverRoute
  SessionsSilverPrimeRoute: typeof SessionsSilverPrimeRoute
  SessionsSilverPrimeLiteRoute: typeof SessionsSilverPrimeLiteRoute
  SessionsVipPlatinumRoute: typeof SessionsVipPlatinumRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsBronzeRoute: SessionsBronzeRoute,
  SessionsGoldRoute: SessionsGoldRoute,
  SessionsGoldPrimeRoute: SessionsGoldPrimeRoute,
  SessionsPlatinumRoute: SessionsPlatinumRoute,
  SessionsSilverRoute: SessionsSilverRoute,
  SessionsSilverPrimeRoute: SessionsSilverPrimeRoute,
  SessionsSilverPrimeLiteRoute: SessionsSilverPrimeLiteRoute,
  SessionsVipPlatinumRoute: SessionsVipPlatinumRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DimensionsRoute: DimensionsRouteWithChildren,
  GetStartedRoute: GetStartedRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  SessionsRoute: SessionsRouteWithChildren,
  TermsRoute: TermsRoute,
  AppBookRoute: AppBookRoute,
  AppVoiceRoomRoute: AppVoiceRoomRoute,
  ShyamBookingsRoute: ShyamBookingsRoute,
  ShyamDashboardRoute: ShyamDashboardRoute,
  ShyamPostsRoute: ShyamPostsRoute,
  ShyamUidSearchRoute: ShyamUidSearchRoute,
  ShyamVoiceRoute: ShyamVoiceRoute,
  AppIndexRoute: AppIndexRoute,
  ShyamIndexRoute: ShyamIndexRoute,
  AppUidUidRoute: AppUidUidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
